management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  server:
    port: 18081

spring:
  application:
    name: demo-springboot

server:
  port: 8081

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://${ZK_HOST:localhost}:2181
  metrics:
    prometheus:
      exporter:
        enabled: true
    enable-rpc: true
    enable-threadpool: true
    enable-metadata: true
    enable-jvm: true
    enable-registry: true
    aggregation:
      enabled: true
      enable-qps: true
      enable-rt: true
      enable-requst: true
      bucket-num: 10
      time-window: 10000
      qps-time-window-mill-seconds: 100
