apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-elk
  template:
    metadata:
      labels:
        app: elasticsearch-elk
    spec:
      containers:
        - name: elasticsearch-elk
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enabled
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-elk
spec:
  type: NodePort
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch-elk
