version: '3.8'

services:
  # Prometheus service
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # 连接到 monitoring 网络
    networks:
      - monitoring
      - backend

  # Grafana service
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    # 连接到 monitoring 网络
    networks:
      - monitoring

  # zookeeper 服务
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    # 连接到 backend 网络
    networks:
      - backend

  # 后台服务
  demo-dubbo:
    build:
      dockerfile: Dockerfile.demo-dubbo
    restart: always
    container_name: demo-dubbo
    image: demo-dubbo
    ports:
      - "8082:8082"
      - "18082:18082"
    environment:
      - ZK_HOST=zookeeper
    # 连接到 backend 网络
    depends_on:
      - zookeeper
    networks:
      - backend

  # 后台服务
  demo-springboot:
    build:
      dockerfile: Dockerfile.demo-springboot
    restart: always
    container_name: demo-springboot
    image: demo-springboot
    ports:
      - "8081:8081"
      - "18081:18081"
    environment:
      - ZK_HOST=zookeeper
    # 连接到 backend 网络
    depends_on:
      - zookeeper
    # 连接到 backend 网络
    networks:
      - backend

# 定义两个网络
networks:
  monitoring:
  backend: