# Stage 1: Build the application
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /home/app

# 将整个父目录全部内容复制到 /home/app
COPY . /home/app

# 用 maven 编译项目
RUN mvn -f /home/app/pom.xml clean package -DskipTests -pl demo-api,demo-dubbo -am

# Stage 2: Create the final image
FROM openjdk:17-jdk-slim
COPY --from=build /home/app/demo-dubbo/target/demo-dubbo-0.0.1-SNAPSHOT.jar /usr/local/lib/demo-dubbo.jar
EXPOSE 8082
EXPOSE 18082
ENTRYPOINT ["java","-jar","/usr/local/lib/demo-dubbo.jar"]