# 全局配置
global:
  # 多久采集一次数据
  scrape_interval: 5s

# 采集配置
scrape_configs:
  # 采集 Spring Boot 应用的数据
  - job_name: 'demo-springboot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'demo-springboot:18081' ]
  - job_name: 'demo-dubbo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'demo-dubbo:18082' ]