# 全局配置
global:
  # 多久采集一次数据
  scrape_interval: 5s

# 采集配置
scrape_configs:
  - job_name: 'prometheus-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'demo-springboot:18081', 'demo-dubbo:18082' ]