{
 "title": "线程池监控",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "应用", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(thread_pool_active_threads{application=\"$application\"},instance)"
    }
   },
   {
    "name": "thread_pool",
    "label": "线程池",
    "query": {
     "query": "label_values(thread_pool_max_pool_size{application=\"$application\"},pool_name)"
    }
   },
   {
    "name": "task_name",
    "label": "任务名称",
    "query": {
     "query": "label_values(task_success_count_qps{application=\"$application\", pool_name=\"$thread_pool\"},task_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "机器总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "系统"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "进程"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "进程-15m"
    }
   ]
  },
  {
   "title": "堆使用量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\",area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "堆使用量"
    }
   ]
  },
  {
   "title": "非堆使用量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "非堆使用量"
    }
   ]
  },
  {
   "title": "线程数总览",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "活跃线程数"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "守护线程数"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "线程数峰值"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "进程数"
    }
   ]
  },
  {
   "title": "线程状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "线程池总数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "count(count by (pool_name) (thread_pool_active_threads{application=\"$application\",instance=\"$instance\"}))",
     "legendFormat": "线程池总数"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\"}",
     "legendFormat": "1分钟平均负载"
    },
    {
     "expr": "system_cpu_count{application=\"$application\"}",
     "legendFormat": "CPU核数"
    }
   ]
  },
  { "title": "线程池汇总", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "线程池[$thread_pool]负载",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thread_pool_active_threads{application=\"$application\", pool_name=\"$thread_pool\", instance=\"$instance\"} + thread_pool_queue_size{application=\"$application\", pool_name=\"$thread_pool\", instance=\"$instance\"})/ (thread_pool_max_pool_size{application=\"$application\", pool_name=\"$thread_pool\", instance=\"$instance\"} + thread_pool_queue_size{application=\"$application\", pool_name=\"$thread_pool\", instance=\"$instance\"} + thread_pool_queue_remaining_capacity{application=\"$application\", pool_name=\"$thread_pool\", instance=\"$instance\"}) * 100",
     "legendFormat": "线程池负载"
    }
   ]
  },
  {
   "title": "线程池[$thread_pool]任务占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_total_count_qps{application=\"$application\", pool_name=\"$thread_pool\", instance=\"$instance\"}) by (task_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "线程池[$thread_pool]汇总",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "thread_pool_active_threads{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"}",
     "legendFormat": "活跃线程数"
    },
    {
     "expr": "thread_pool_core_pool_size{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"}",
     "legendFormat": "核心线程数"
    },
    {
     "expr": "thread_pool_max_pool_size{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"}",
     "legendFormat": "最大线程数"
    },
    {
     "expr": "thread_pool_queue_size{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"}",
     "legendFormat": "队列大小"
    },
    {
     "expr": "thread_pool_queue_remaining_capacity{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"}",
     "legendFormat": "剩余队列容量"
    },
    {
     "expr": "sum(task_total_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"})",
     "legendFormat": "总任务数QPS"
    },
    {
     "expr": "sum(task_success_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"})",
     "legendFormat": "总成功数QPS"
    },
    {
     "expr": "sum(task_failure_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"})",
     "legendFormat": "总失败数QPS"
    },
    {
     "expr": "sum(task_rejected_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\"})",
     "legendFormat": "总拒绝数QPS"
    }
   ]
  },
  { "title": "任务详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "任务[$task_name]监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "repeat": "task_name",
   "targets": [
    {
     "expr": "task_success_count_qps{application=\"$application\", instance=\"$instance\",pool_name=\"$thread_pool\", task_name=\"$task_name\"} / task_total_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\", task_name=\"$task_name\"} * 100",
     "legendFormat": "成功率%"
    },
    {
     "expr": "task_total_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\", task_name=\"$task_name\"}",
     "legendFormat": "总数QPS"
    },
    {
     "expr": "task_success_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\", task_name=\"$task_name\"}",
     "legendFormat": "成功数QPS"
    },
    {
     "expr": "task_failure_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\", task_name=\"$task_name\"}",
     "legendFormat": "失败数QPS"
    },
    {
     "expr": "task_rejected_count_qps{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\", task_name=\"$task_name\"}",
     "legendFormat": "拒绝数QPS"
    },
    {
     "expr": "task_rt{application=\"$application\", instance=\"$instance\", pool_name=\"$thread_pool\", task_name=\"$task_name\"}",
     "legendFormat": "RT"
    }
   ]
  }
 ]
}