server:
  port: 8088
spring:
  profiles:
    active: dev
  application:
    name: sharding-boot-demo
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config-${spring.profiles.active}.yaml
  jpa:
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC+8
    database: mysql

logging:
  level:
    com.oneinstep: DEBUG
